### PR TITLE
Fix gazelle overwriting matching rules

### LINKED ISSUE #41: gazelle plugin always overwrites existing buf_breaking_test
When in `package` mode, the gazelle plugin is always overwriting existing `buf_breaking_test` rules instead of merging them. 
In my case, I've set the `size` attribute on my rule but it gets removed on each invocation of gazelle.

There is a code path in [generate.go](https://github.com/bufbuild/rules_buf/blob/abbbfce7c3fccf1d4b87afa28140d9ce53f80057/gazelle/buf/generate.go#L136) to handle this case but the check is sensitive to the `targets` exactly matching the key in `protoRuleMap`.

The [protoRuleMap](https://github.com/bufbuild/rules_buf/blob/abbbfce7c3fccf1d4b87afa28140d9ce53f80057/gazelle/buf/generate.go#L43-L44) is populated from a rule's `name` attribute, but the lookup is using another rule's [targets](https://github.com/bufbuild/rules_buf/blob/abbbfce7c3fccf1d4b87afa28140d9ce53f80057/gazelle/buf/generate.go#L131) attribute. The `targets` attribute is a set of labels so they are typically prepended with a colon (e.g. `:protos` vs `protos`). As a result, the `targets` never match a value in `protoRuleMap` and any existing `buf_breaking_test` rule is removed instead of merged.

Here's an example of my patch to work around this.
```diff
 gazelle/buf/generate.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/gazelle/buf/generate.go b/gazelle/buf/generate.go
index 7766961..0f8aed9 100644
--- a/gazelle/buf/generate.go
+++ b/gazelle/buf/generate.go
@@ -133,7 +133,7 @@ func shouldRemoveSingleTargetBufRule(
 		// Not generated by us
 		return false
 	}
-	if len(targets) == 1 && protoRuleMap[targets[0]] != nil {
+	if len(targets) == 1 && protoRuleMap[strings.TrimPrefix(targets[0], ":")] != nil {
 		// Target is accurate so skip
 		return false
 	}
```

### PR DESCRIPTION
**Pull request by srikrsna-buf**
Fix gazelle overwriting matching rules. The problem and solution identified in #41. Closes #41

### CODE REVIEW

File: gazelle/buf/generate.go [hunk 1]
```diff
@@ -133,7 +133,7 @@ func shouldRemoveSingleTargetBufRule(
 		// Not generated by us
 		return false
 	}
-	if len(targets) == 1 && protoRuleMap[targets[0]] != nil {
+	if len(targets) == 1 && protoRuleMap[strings.TrimPrefix(targets[0], ":")] != nil {
```
Comment (emcfarlane) [inline gazelle/buf/generate.go:136]: Why do you not need to still check `protoRuleMap[targets[0]]`?

**Review by emcfarlane — APPROVED** [review]
lgtm

File: gazelle/buf/generate.go (hunk 1 above)
Comment (emcfarlane) [reply gazelle/buf/generate.go:136]: Ah both `:foo_proto` resolve to `foo_proto`.
